# Generated by Django 4.0.4 on 2022-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalSell',
            field=models.IntegerField(default=0),
        ),
    ]
