# Generated by Django 4.0.4 on 2022-05-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0004_product_totalsell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='totalSell',
            field=models.IntegerField(),
        ),
    ]
