# Generated by Django 4.0.4 on 2022-05-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0005_alter_product_totalsell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='totalSell',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
