# Generated by Django 4.0.4 on 2022-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0006_remove_product_totalsell_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
