# Generated by Django 4.0.4 on 2022-05-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0004_product_description'),
        ('caliza', '0008_alter_product_price'),
    ]

    operations = [
    ]
