# Generated by Django 4.0.4 on 2022-06-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0010_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caliza.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caliza.product')),
            ],
        ),
    ]
