# Generated by Django 4.0.4 on 2022-06-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0010_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
