# Generated by Django 4.0.4 on 2022-06-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0012_getproducts_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getproducts',
            name='quantity',
        ),
    ]
