# Generated by Django 4.0.4 on 2022-06-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0011_prueba'),
        ('caliza', '0013_remove_getproducts_quantity'),
    ]

    operations = [
    ]
