# Generated by Django 4.0.4 on 2022-06-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caliza', '0014_merge_0011_prueba_0013_remove_getproducts_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
